[project]
name = "formula1"
version = "0.1.0"
description = "Statistiques interactives sur la Formule 1."
requires-python = ">=3.9"
dependencies = [
    "streamlit",
    "fastf1",
    "pandas",
    "matplotlib",
    "plotly",
    "streamlit-extras",
    "numpy>=2.0.2",
]
